package br.com.loja.pdv.domain.enums;

public enum Permissao {
    USUARIOS, PRODUTOS, PRECOS, ESTOQUE, VENDAS, CAIXA,
    RELATORIOS, CONFIGURACOES, BACKUP, DESCONTOS, CANCELAMENTOS,
    REIMPRESSAO, FECHAR_PROPRIO_CAIXA
}
